# Generated by Django 3.2.7 on 2021-09-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210914_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='eh_cliente',
        ),
    ]
